### ISSUE TITLE
Hard-coded git.exe and TortoiseGitProc.exe paths 

### ISSUE THREAD

**Issue by min2sia** [Go-ERP/Ax2Git#3]
Now paths to Git and TortoiseGit executables are hard-coded in `classDeclaration` of the `Git` class:

```
class Git
{
    #localmacro.git
        @'C:\Program Files (x86)\Git\bin\git.exe'
    #endmacro

    #localmacro.TortoiseGit
        @'C:\Program Files\TortoiseGit\bin\TortoiseGitProc.exe'
    #endmacro
}
```

Probably it would be better to have it in user-accessible parameters form?

**Comment by ksix** [comment]
It should just use git from the env path, not using a git.exe location.

**Comment by kevinkabatra** [comment]
One thing to keep in mind is that these features will not be available for Dynamics 365 for Operations as over layering will be prevented in the future. So any work spent on these tasks will only benefit those using AX 2012. Now the AX 2012 install base is obviously larger at the moment, but I feel that work should be done that will benefit both products or at least be future compatible. 

I agree that hard-coding is not ideal but this product is towards the end of its life.

**Comment by ksix** [comment]
Dynamics 365 is almost a completely different product, it also already supports GIT natively. I'm looking at this as I have several large projects which will continue with AX 2012 for at least 5 more years, so is worth it for us.

**Comment by kevinkabatra** [comment]
Totally makes sense in that regard. One thing to note though is that at the D365 Tech Conference MS states  that they will not be supporting GIT. While they are using VSTS, which supports GIT, they said that at this time there is no GIT support. I am sure there are ways around that, but officially you would be on your own. Adding a screenshot from the presentation.

Also on a side note I am not sure if this project still has any development from the original author. 

At one point I was looking into the SysVersionControl tables and forms to add this functionality into the system. So that it can replace the current system altogether. You might want to approach the project from that aspect. If you have any questions I would be glad to help.

![image](https://cloud.githubusercontent.com/assets/7569534/24125257/341ebc66-0d9e-11e7-8574-f8d7716266d0.png)

**Comment by min2sia** [comment]
Sorry for delayed response, I just now (accidentally) noticed there were comments on this repo. Somehow I never saw any notifications from Github .

Just to make it clear: yes, this project can only be used with Ax 2012 (and can be adapted to earlier versions). D365 is a totally different thing, with different approach to source control.

**Comment by min2sia** [comment]
Both Git for windows and TortoiseGit installers add their paths to system PATH, so there is no need to specify full path to both executables.
